### ISSUE TITLE
Example in readme fails with Exception: Solver failed with status 3

### ISSUE THREAD

**Issue by laurenceyang33** [SBRG/minspan#1]
The example in README fails using:
- textbook model
- gurobi

from minspan import minspan, nnz
from cobra.test import create_test_model

model = create_test_model('textbook')
solved_fluxes = minspan(model, cores=1, verbose=True)
print 'nnz', nnz(solved_fluxes)

Runs fine until this error:

/home/laurence/.local/lib/python2.7/site-packages/minspan-0.1.0-py2.7.egg/minspan.pyc in calculate_minspan_column(model_pickle, original_fluxes, column_index, N, cores, timelimit, verbose, solver_name)
    301         elif solver_name.startswith("gurobi"):
    302             status = lp.status
--> 303         raise Exception("Solver failed with status %s" % status)
    304     return flux
    305 

**Exception: Solver failed with status 3**

**Comment by aebrahim** [comment]
I believe the example in the readme is actually a little bit different. It has

`model = load_matlab_model("testing_models.mat", "ecoli_core")`

Does that at least work?

**Comment by aebrahim** [comment]
The reason the `create_test_model('textbook')` version  failed is because that model has not been prepared for minspan. It still needs to have all the blocked reactions pruned.

This should work:

```
from minspan import minspan, nnz, prepare_model
import cobra.test

t = cobra.test.create_test_model('textbook')
t.reactions.Biomass_Ecoli_core.remove_from_model()
prepare_model(t)

# remove blocked reactions
res = cobra.flux_analysis.flux_variability_analysis(t)
blocked_reactions = [i for i in res if res[i]["maximum"] == res[i]["minimum"]]
t.remove_reactions(blocked_reactions)

solved_fluxes = minspan(t, verbose=False)
print 'nnz', nnz(solved_fluxes)
```
